#' Run an APSIM-X Simulation
#' 
#' A valid apsimx file can be run from within R. The main goal is to make running APSIM-X
#' simple, especially for large scale simulations or parameter optimization
#' 
#' @title Run an APSIM-X simulation
#' @name apsimx
#' @description Run apsimx from R. It uses 'system' (unix) or 'shell' (windows) and it attempts to be platform independent.
#' @param file file name to be run (the extension .apsimx is optional)
#' @param src.dir directory containing the .apsimx file to be run (defaults to the current directory)
#' @param silent whether to print messages from apsim simulation
#' @param value how much output to return: \cr
#'              option 'all' returns all components of the simulation; \cr
#'              option 'report' returns only the 'main' report component; \cr
#'              option 'none' does not create a data.frame but it generates the databases from APSIM-X
#' @param cleanup logical. Whether to delete the .db file generated by APSIM-X. Default is FALSE
#' @export
#' @examples 
#' \dontrun{
#' ## See function 'apsimx_example' 
#' }
#'

apsimx <- function(file = "", src.dir=".",
                   silent = FALSE, 
                   value = c("all","report","none"),
                   cleanup = FALSE){
  
  value <- match.arg(value)
  
  if(file == "") stop("need to specify file name")
  
  ## The following lines are somewhat not needed
  fileNames <- dir(path = src.dir, pattern=".apsimx$",ignore.case=TRUE)
  
  file <- match.arg(file, fileNames, several.ok=FALSE)
  
  if(length(fileNames)==0){
    stop("There are no .apsimx files in the specified directory to run.")
  }
  
  if(length(grep(".apsimx$",file)) != 0){
    ## I assume the extention was included
    ## Only use the name from here 
    file <- strsplit(file, ".", fixed = TRUE)[[1]][1]
  }
  
  file.name.path <- paste0(src.dir,"/",file)
  
  ada <- auto_detect_apsimx()

  if(.Platform$OS.type == "unix"){
    mono <- system("which mono", intern = TRUE)
    run.strng <- paste0(mono," ",ada," ",file.name.path,".apsimx")
    ## Run APSIM-X on the command line
    system(command = run.strng, ignore.stdout = silent)
  }
  
  if(.Platform$OS.type == "windows"){
    if(src.dir != ".") stop("In Windows you can only run a file from the current directory.")
    run.strng <- paste0(ada," ",file.name.path,".apsimx")
    shell(cmd = run.strng, translate = TRUE, intern = TRUE)
  }

  if(value != "none"){
    ans <- read_apsimx(file = file, src.dir = src.dir, value = value)
  }else{
    if(value == "none" & !silent){
      cat("APSIM created .db files, but nothing is returned \n")
    }
  }
  
  if(cleanup){
    ## Default is not to cleanup
    if(value == "none") stop("do not clean up if you choose value = 'none' ")
    ## Delete the apsim-generated sql database 
    file.remove(paste0("./",file.name.path,".db"))
  }
  
  if(value != "none")
    return(ans)
}

## This is an internal function so I won't export/document it
auto_detect_apsimx <- function(){

  ## Internal function to split APSIM name
  fev <- function(x) as.numeric(strsplit(x, ".", fixed = TRUE)[[1]][4])
  ## I need to deal with the fact that there might be multiple versions
  ## of APSIM installed
  
  if(.Platform$OS.type == "unix"){

    if(grepl("Darwin", Sys.info()[["sysname"]])){
      laf <- list.files("/Applications/")
      find.apsim <- grep("APSIM",laf)
      if(length(find.apsim) > 1){
        apsimx.versions <- sapply(laf[find.apsim],fev)
        newest.version <- sort(apsimx.versions, decreasing = TRUE)[1]
        if(apsimx::apsimx.options$warn.versions){
           warning(paste("Multiple versions of APSIM-X installed. \n
                    Choosing the newest one:",newest.version))
        }
        apsimx.name <- grep(newest.version, laf[find.apsim], value = TRUE)
      }else{
        apsimx.name <- laf[find.apsim]
      }
      ## APSIM executable
      st1 <- "/Applications/"
      st3 <- "/Contents/Resources/Bin/Models.exe" 
      apsimx_dir <- paste0(st1,apsimx.name,st3)
    }
  
    if(grepl("Linux", Sys.info()[["sysname"]])){
      apsimx.versions <- list.files("/usr/local/lib/apsim")
      if(length(apsimx.versions) > 1){
        versions <- sapply(apsimx.versions, fev)
        newest.version <- sort(versions, decreasing = TRUE)[1]
        if(apsimx::apsimx.options$warn.versions){
          warning(paste("Multiple versions of APSIM-X installed. \n
                    Choosing the newest one:",newest.version))
        }
        apsimx.name <- grep(newest.version, apsimx.versions, value = TRUE)
      }else{
        apsimx.name <- apsimx.versions
      }
      ## APSIM executable
      st1 <- "/usr/local/lib/apsim/"
      st3 <- "/Bin/Models.exe" 
      apsimx_dir <- paste0(st1,apsimx.name,st3)
    }
  }
  
  if(.Platform$OS.type == "windows"){
    st1 <- "C:/PROGRA~1/"
    laf <- list.files(st1)
    find.apsim <- grep("APSIM",laf)
    apsimx.versions <- laf[find.apsim]
    if(length(find.apsim) > 1){
      versions <- sapply(apsimx.versions, fev)
      newest.version <- sort(versions, decreasing = TRUE)[1]
      if(apsimx::apsimx.options$warn.versions){
        warning(paste("Multiple versions of APSIM-X installed. \n
                    Choosing the newest one:",newest.version))
      }
      apsimx.name <- grep(newest.version, apsimx.versions, value = TRUE)
    }else{
      apsimx.name <- laf[find.apsim]
    }
    ## APSIM executable
    st3 <- "/Bin/Models.exe" 
    apsimx_dir <- paste0(st1,apsimx.name,st3)
  }
  
  if(!is.na(apsimx::apsimx.options$exe.path)){
    ## Windows paths can contain white spaces which are
    ## problematic when running them at the command line
    ## shQuote might be useful for this purpose
    apsimx_dir <- shQuote(apsimx::apsimx.options$exe.path)
  }
  return(apsimx_dir)
}

#' Auto detect where apsimx examples are located 
#' 
#' @title Auto detect where apsimx examples are located
#' @name auto_detect_apsimx_examples
#' @description simple function to detect where APSIM-X examples are located
#' @return will create a directory pointing to APSIM-X distributed examples
#' @export
#' @examples 
#' \dontrun{
#' ex.dir <- auto_detect_apsimx_examples()
#' }
#' 

auto_detect_apsimx_examples <- function(){
  
  ## Internal function to split APSIM name
  fev <- function(x) as.numeric(strsplit(x, ".", fixed = TRUE)[[1]][4])
  
  if(.Platform$OS.type == "unix"){
    apsim.name <- NULL
    if(grepl("Darwin", Sys.info()[["sysname"]])){
      ## If APSIM-X is installed it will be in /Applications/
      ## look into Applications folder
      laf <- list.files("/Applications/")
      find.apsim <- grep("APSIM",laf)
      if(length(find.apsim) > 1){
        apsimx.versions <- sapply(laf[find.apsim],fev)
        newest.version <- sort(apsimx.versions, decreasing = TRUE)[1]
        if(apsimx::apsimx.options$warn.versions){
          warning(paste("Multiple versions of APSIM-X installed. \n
                    Choosing the newest one:",newest.version))
        }
        apsimx.name <- grep(newest.version, laf[find.apsim], value = TRUE)
      }else{
        apsimx.name <- laf[find.apsim]
      }
      st1 <- "/Applications/"
      st3 <- "/Contents/Resources/Examples" 
      apsimx_ex_dir <- paste0(st1,apsimx.name,st3)
      return(apsimx_ex_dir)
    }
  
    if(grepl("Linux", Sys.info()[["sysname"]])){
      st1 <- "/usr/local/lib/apsim/"
      apsimx.versions <- list.files(st1) 
      if(length(apsimx.versions) > 1){
        versions <- sapply(apsimx.versions, fev)
        newest.version <- sort(versions, decreasing = TRUE)[1]
        if(apsimx.options$warn.versions){
          warning(paste("Multiple versions of APSIM-X installed. \n
                    Choosing the newest one:",newest.version))
        }
        apsimx.name <- grep(newest.version, apsimx.versions, value = TRUE)
      }else{
        apsimx.name <- apsimx.versions
      }
      apsimx_ex_dir <- paste0(st1,apsimx.name,"/Examples")
    }
  }
  
  if(.Platform$OS.type == "windows"){
      st1 <- "C:/PROGRA~1"
      laf <- list.files(st1)
      find.apsim <- grep("APSIM",laf)
      apsimx.versions <- laf[find.apsim]
      if(length(apsimx.versions) > 1){
        versions <- sapply(apsimx.versions, fev)
        newest.version <- sort(versions, decreasing = TRUE)[1]
        warning(paste("Multiple versions of APSIM-X installed. \n
                    Choosing the newest one:",newest.version))
        apsimx.name <- grep(newest.version, apsimx.versions, value = TRUE)
      }else{
        apsimx.name <- apsimx.versions
      }
      ## APSIM path to examples
      st3 <- "/Examples" 
      apsimx_ex_dir <- paste0(st1,"/",apsimx.name,st3)
  }
  
  if(!is.na(apsimx::apsimx.options$examples.path)){
    ## Not sure if I need shQuote here
    apsimx_ex_dir <- apsimx::apsimx.options$examples.path
  }
  return(apsimx_ex_dir)
}

#'
#' @title Access Example APSIM-X Simulations
#' @name apsimx_example
#' @description simple function to run some of the built-in APSIM-X examples
#' @param example run an example from built-in APSIM-X. Options are all of the ones included with the APSIM-X distribution, except 'Graph'.
#' @param silent whether to print standard output from the APSIM-X execution
#' @note This function creates a new column 'Date' which is in the R 'Date' format which is convenient for graphics.
#' @details This function creates a temporary copy of the example file distributed with APSIM-X to avoid writing a .db file 
#'          to the directory where the 'Examples' are located. It is not a good practice and there is no guarantee that 
#'          the user has read/write permissions in that directory.
#' @export
#' @examples 
#' \dontrun{
#' wheat <- apsimx_example("Wheat")
#' maize <- apsimx_example("Maize")
#' barley <- apsimx_example("Barley")
#' ## The 'Date' column is created by this function, based on apsim output.
#' ggplot(data = wheat , aes(x = Date, y = Yield)) + 
#'   geom_point()
#' }
#' 

apsimx_example <- function(example = "Wheat", silent = FALSE){

  ## Run a limited set of examples
  ## Now the only one missing is Graph, which I assume is about
  ## graphics and not that relevant to apsimx
  ## Several examples are not supported because they do not use
  ## relative paths for the weather file
  ex.ch <- c("Barley","ControlledEnvironment",
             "Eucalyptus", "EucalyptusRotation",
             "Maize","Oats", "SCRUM", "Sugarcane",
             "Wheat")
  
  example <- match.arg(example, choices = ex.ch)
  
  ada <- auto_detect_apsimx()
  apsimx_options(warn.versions = FALSE)
  ex.dir <- auto_detect_apsimx_examples()
  apsimx_options(warn.versions = TRUE)
  ex <- paste0(ex.dir,"/",example,".apsimx")
  
  if(!file.exists(ex)) stop("cannot find example files")
  ## Make a temporary copy of the file to the current directory
  ## Do not transfer permissions?
  file.copy(from = ex, to = ".", copy.mode = FALSE)
  
  ## Need to edit the met file path
  met.path <- capture.output(inspect_apsimx(example, src.dir = ex.dir, node = "Weather"))
  
  if(!grepl("%root%", met.path, fixed = TRUE)){
    curr.met.path <- gsub("\\","/",strsplit(met.path, " ")[[1]][3], fixed = TRUE)
    new.met.path <- paste0(ex.dir,"/",curr.met.path)
    edit_apsimx(example, node = "Weather", 
                value = new.met.path, 
                overwrite = TRUE, 
                verbose = FALSE)
  }
  
  if(.Platform$OS.type == "unix"){
    mono <- system("which mono", intern = TRUE)
    run.strng <- paste0(mono," ",ada," ./",paste0(example,".apsimx"))
    ## Run APSIM
    system(command = run.strng, ignore.stdout = silent)
  }
  
  if(.Platform$OS.type == "windows"){
    run.strng <- paste0(ada," ",paste0("./",example,".apsimx"))
    shell(cmd = run.strng, translate = TRUE, intern = TRUE)
  }

  ## Create database connection
  ## I don't need to specify the directory as it should be the current one
  ans <- read_apsimx(paste0(example,".db"), value = "report")
  ## OS independent cleanup (risky?)
  file.remove(paste0("./",example,".db"))
  file.remove(paste0("./",example,".apsimx"))
  ## Add the date
  ans$Date <- as.Date(sapply(ans$Clock.Today, function(x) strsplit(x, " ")[[1]][1]))
  ## Return data frame
  return(ans)
}

#' Read APSIM-X generated .db files
#' 
#' @title Read APSIM-X generated .db files
#' @name read_apsimx
#' @description read SQLite databases created by APSIM-X runs. One file at a time.
#' @param file file name
#' @param src.dir source directory where file is located
#' @param value either 'report' (data.frame) or 'all' (list)
#' @export
#' 

read_apsimx <- function(file = "", src.dir = ".",
                        value = c("report","all")){
  
  if(file == "") stop("need to specify file name")
  
  fileNames <- dir(path = src.dir, pattern=".db$",ignore.case=TRUE)
  
  if(length(fileNames)==0){
    stop("There are no .db files in the specified directory to read.")
  }
  
  value <- match.arg(value)
  
  if(length(grep(".db$",file)) != 0){
    ## I assume the extention was included
    ## Only use the name from here 
    ## This strips the extension
    file <- strsplit(file, ".", fixed = TRUE)[[1]][1]
  }
  
  file.name.path <- paste0(src.dir,"/",file)
  
  con <- DBI::dbConnect(RSQLite::SQLite(), paste0(file.name.path,".db"))
  ## create data frame for each table
  tbl0 <- DBI::dbGetQuery(con, "SELECT * FROM Report")
  tbl1 <- DBI::dbGetQuery(con, "SELECT * FROM _Checkpoints")
  tbl2 <- DBI::dbGetQuery(con, "SELECT * FROM _InitialConditions")
  tbl3 <- DBI::dbGetQuery(con, "SELECT * FROM _Messages")
  tbl4 <- DBI::dbGetQuery(con, "SELECT * FROM _Simulations")
  tbl5 <- DBI::dbGetQuery(con, "SELECT * FROM _Units")
  ## Disconnect
  DBI::dbDisconnect(con)
  
  if(any(grepl("Clock.Today",names(tbl0)))){
    tbl0$Date <- as.Date(sapply(tbl0$Clock.Today, function(x) strsplit(x, " ")[[1]][1]))
  }
  ## Return list
  if(value == "all"){
    ans <- list(Report = tbl0, Checkpoints = tbl1, InitialConditions = tbl2,
                Messages = tbl3, Simulations = tbl4, Units = tbl5)
  }
  ## Return data.frame
  if(value == "report"){
    ans <- tbl0
  }
  return(ans)
}

#' Read all APSIM-X generated .db files in a directory
#' 
#' @title Read all APSIM-X generated .db files in a directory
#' @name read_apsimx_all
#' @description Like 'read_apsimx', but it reads all .db files in a directory. 
#' @param src.dir source directory where files are located
#' @param value either 'report' or 'all' (only 'report' implemented at the moment)
#' @note Warning: very simple function at the moment, not optimized for memory or speed.
#' @export
#' 

read_apsimx_all <- function(src.dir = ".", value = c("report","all")){
  
  ## This is super memorey hungry and not efficient at all, but it might work 
  ## for now
  
  value <- match.arg(value)
  
  fileNames <- dir(path = src.dir, pattern=".db$",ignore.case=TRUE)
  
  ans <- NULL
  
  for(i in fileNames){
    
    tmp <- read_apsimx(fileNames[i], value = value)
    tmp.d <- data.frame(file.name = fileNames[i], tmp)
    ans <- rbind(ans, tmp)
    
  }
  return(ans)
}

#' Set apsimx options
#' 
#' @title Setting some options for the package
#' @name apsimx_options
#' @description Set the path to the APSIM-X executable, examples and warning suppression. 
#' @param exe.path path to apsim executable
#' @param examples.path path to apsim examples
#' @param warn.versions logical. warning if multiple versions of APSIM-X are detected.
#' @note It is possible that APSIM-X is installed in some alternative location other than the 
#'       defaults ones. Guessing this can be difficult and then the auto_detect functions might
#'       fail. Also, if multiple versions of APSIM-X are installed apsimx will choose the newest
#'       one but it will issue a warning. Suppress the warning by setting warn.versions = FLASE.
#' @export
#' @examples 
#'\dontrun{
#' names(apsimx.options)
#' apsimx_options(exe.path = "some-new-path-to-executable")
#' apsimx.options$exe.path
#' }

apsimx_options <- function(exe.path = NA, examples.path = NA, warn.versions = TRUE){
  assign('exe.path', exe.path, apsimx.options)
  assign('examples.path', examples.path, apsimx.options)
  assign('warn.versions', warn.versions, apsimx.options)
}

#' Environment which stores APSIM-X options
#' 
#' @title Environment which stores APSIM-X options
#' @name apsimx.options
#' @description Environment which can store the path to the executable and where examples are located.
#'              Creating an environment avoids the use of global variables or other similar practices
#'              which would have possible undesriable consequences. 
#' @export
#' @examples 
#' \dontrun{
#' names(apsimx.options)
#' apsimx_options(exe.path = "some-new-path-to-executable")
#' apsimx.options$exe.path
#' }
#' 

apsimx.options <- new.env(parent = emptyenv())
assign('exe.path', NA, apsimx.options)
assign('examples.path', NA, apsimx.options)
assign('warn.versions', TRUE, apsimx.options)

#' Import packages needed for apsimx to work correctly
#' @import DBI jsonlite knitr RSQLite xml2 
#' @importFrom utils read.table
NULL

